# Generated by Django 5.0.1 on 2024-02-07 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('created_at', models.DateField()),
                ('company_name', models.CharField(default='random ', max_length=50)),
                ('logo', models.ImageField(upload_to='media/companylogos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('category', models.CharField(default='information technology', max_length=50)),
                ('Location', models.CharField(default=' ', max_length=100)),
                ('short_desc', models.TextField(max_length=255, verbose_name='Short Description')),
                ('long_desc', models.TextField(max_length=255, verbose_name='Short Description')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
