# Generated by Django 5.0.1 on 2024-02-08 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='logo',
            field=models.ImageField(default=None, upload_to='companylogos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
