# Generated by Django 4.2.10 on 2024-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
