# Generated by Django 5.0.1 on 2024-01-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hireme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Hireme.user')),
                ('company_name', models.CharField(default='', max_length=23)),
            ],
            bases=('Hireme.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default=None, upload_to='media'),
        ),
    ]
