# Generated by Django 4.2.9 on 2024-01-30 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hireme', '0002_employer_alter_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default=None, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
