# Generated by Django 5.0.1 on 2024-02-07 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hireme', '0004_remove_user_resume_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='jobposition',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='resume',
            field=models.FileField(default=None, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv'])]),
        ),
    ]
